#!/bin/sh
code --install-extension ask-toolkit.alexa-skills-kit-toolkit
code --install-extension austin.code-gnu-global
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension CADENAS.vscode-glsllint
code --install-extension chriskirknielsen.visubezier
code --install-extension circledev.glsl-canvas
code --install-extension cocopon.iceberg-theme
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension dtsvet.vscode-wasm
code --install-extension eamodio.amethyst-theme
code --install-extension elmTooling.elm-ls-vscode
code --install-extension esbenp.prettier-vscode
code --install-extension FallenMax.styled-components-extractor
code --install-extension felixfbecker.php-intellisense
code --install-extension golang.go
code --install-extension henoc.svgeditor
code --install-extension Hridoy.gsap-snippets
code --install-extension James-Yu.latex-workshop
code --install-extension jcbuisson.vue
code --install-extension jonkwheeler.styled-components-snippets
code --install-extension justusadam.language-haskell
code --install-extension Kelvin.vscode-sshfs
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension liviuschera.noctis
code --install-extension mf.vscode-styled-components
code --install-extension millennIumAMbiguity.processing-formatter
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension prograhammer.tslint-vue
code --install-extension rahmanyerli.ra-candy
code --install-extension rahmanyerli.ra-silver
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension rocketseat.rocketseatreactjs
code --install-extension rocketseat.rocketseatreactnative
code --install-extension silvenon.mdx
code --install-extension slevesque.shader
code --install-extension toba.vsfire
code --install-extension Tobiah.language-pde
code --install-extension torn4dom4n.latex-support
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wesbos.theme-cobalt2
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xr0master.webstorm-intellij-darcula-theme
code --install-extension yzhang.markdown-all-in-one
code --install-extension ask-toolkit.alexa-skills-kit-toolkit
code --install-extension austin.code-gnu-global
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension CADENAS.vscode-glsllint
code --install-extension chriskirknielsen.visubezier
code --install-extension circledev.glsl-canvas
code --install-extension cocopon.iceberg-theme
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension dtsvet.vscode-wasm
code --install-extension eamodio.amethyst-theme
code --install-extension eamodio.gitlens
code --install-extension elmTooling.elm-ls-vscode
code --install-extension esbenp.prettier-vscode
code --install-extension FallenMax.styled-components-extractor
code --install-extension felixfbecker.php-intellisense
code --install-extension golang.go
code --install-extension henoc.svgeditor
code --install-extension Hridoy.gsap-snippets
code --install-extension James-Yu.latex-workshop
code --install-extension jcbuisson.vue
code --install-extension jonkwheeler.styled-components-snippets
code --install-extension justusadam.language-haskell
code --install-extension Kelvin.vscode-sshfs
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension liviuschera.noctis
code --install-extension mf.vscode-styled-components
code --install-extension millennIumAMbiguity.processing-formatter
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension prograhammer.tslint-vue
code --install-extension rahmanyerli.ra-candy
code --install-extension rahmanyerli.ra-silver
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension rocketseat.rocketseatreactjs
code --install-extension rocketseat.rocketseatreactnative
code --install-extension silvenon.mdx
code --install-extension slevesque.shader
code --install-extension toba.vsfire
code --install-extension Tobiah.language-pde
code --install-extension torn4dom4n.latex-support
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wesbos.theme-cobalt2
code --install-extension wingrunr21.vscode-ruby
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xr0master.webstorm-intellij-darcula-theme
code --install-extension yzhang.markdown-all-in-one
